{% set name = "seamm-util" %}
{% set version = "2024.8.22" %}
{% set sha256 = "f1b2053573df18df2e6af7d63539312ce9a164059c160e71c135f0dd02fedba7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/seamm-util/seamm_util-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pint
    - python >={{ python_min }}
    - requests
    - statsmodels

test:
  imports:
    - seamm_util
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/molssi-seamm/seamm_util
  summary: Utility classes and functions for the SEAMM environment.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/seamm_util/

extra:
  recipe-maintainers:
    - paulsaxe
