{% set name = "seamm-util" %}
{% set version = "2022.11.3" %}
{% set sha256 = "0608f773a31883559e286e402672315eadb8b5ac6d8488d72d947accdc823a12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/seamm-util/seamm_util-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - pint
    - python >=3.8
    - requests
    - statsmodels

test:
  imports:
    - seamm_util
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/molssi-seamm/seamm_util
  summary: Utility classes and functions for the SEAMM environment.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/seamm_util/

extra:
  recipe-maintainers:
    - paulsaxe
