{% set name = "seamm-util" %}
{% set version = "2025.8.27" %}
{% set sha256 = "8633dc73a0fc43f70d509ac9155ee2d65fd739678d7fd96619c6fcce3d87815a" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/seamm-util/seamm_util-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pint
    - plotly
    - python >={{ python_min }}
    - requests
    - statsmodels

test:
  imports:
    - seamm_util
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/molssi-seamm/seamm_util
  summary: Utility classes and functions for the SEAMM environment.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/seamm_util/

extra:
  recipe-maintainers:
    - paulsaxe
