{% set name = "seamm-util" %}
{% set version = "2026.9.18" %}
{% set sha256 = "a5f4704e22357d4500d48e1833f7afb829ef3196c2b757e9cc69a9f7beeaba5b" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/s/seamm-util/seamm_util-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pint
    - plotly
    - python >={{ python_min }}
    - requests
    - statsmodels

test:
  imports:
    - seamm_util
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/molssi-seamm/seamm_util
  summary: Utility classes and functions for the SEAMM environment.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://molssi-seamm.github.io/seamm_util/

extra:
  recipe-maintainers:
    - paulsaxe
